"""EcoFlow cloud transport constants."""

IOT_API_BASE = "https://api-e.ecoflow.com"
MQTT_HOST = "mqtt-e.ecoflow.com"
MQTT_PORT_TCP = 8883
MQTT_PORT_WSS = 8084
MQTT_WSS_PATH = "/mqtt"
DEFAULT_MQTT_KEEPALIVE = 60
DEFAULT_WSS_KEEPALIVE = 60
DEFAULT_RECONNECT_DELAY = 2
DEFAULT_MAX_RECONNECT_DELAY = 300
DEFAULT_MAX_RECONNECT_ATTEMPTS = 10
DEFAULT_COUNTER_RESET_INTERVAL = 300
