protocol_test_solar_minimum_field_only:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: "ecoflow_powerpulse2"
    confirm_protocol_test:
      required: true
      selector:
        boolean: {}
    current:
      required: true
      selector:
        number:
          min: 6
          max: 16
          step: 1
          unit_of_measurement: "A"
          mode: "box"
    expected_work_mode:
      required: true
      selector:
        select:
          options: ["solar", "fast"]
    expected_continuous_charging:
      required: false
      selector:
        boolean: {}

protocol_test_custom_current_field_only:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: "ecoflow_powerpulse2"
    confirm_protocol_test:
      required: true
      selector:
        boolean: {}
    current:
      required: true
      selector:
        number:
          min: 6
          max: 16
          step: 1
          unit_of_measurement: "A"
          mode: "box"
    expected_work_mode:
      required: true
      selector:
        select:
          options: ["solar", "fast"]

protocol_test_phase_while_charging:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: "ecoflow_powerpulse2"
    confirm_protocol_test:
      required: true
      selector:
        boolean: {}
    phase:
      required: true
      selector:
        select:
          options: ["auto", "one_phase", "three_phase"]


protocol_test_continuous_field_only:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: "ecoflow_powerpulse2"
    confirm_protocol_test:
      required: true
      selector:
        boolean: {}
    enabled:
      required: true
      selector:
        boolean: {}
